Conversation state working
MeltanoLabs/tap-messagebird pull request #45
Opened 2023-05-01 16:43 UTC by visch

Closes #17

2023-05-01 16:45 UTC, visch commented on tap_messagebird/streams.py
> +    """Conversation is archived and we recieved an error."""
whoops, fixing

2023-05-01 16:57 UTC, visch commented on tap_messagebird/streams.py
> -    def get_url_params(
From looking at produciton data, most conversations don't have a ton of back and forth so also keeping a state tracker for number of messages is probably overboard. We could but I wanted to get rid of the complexity and potential for something messing up

2023-05-03 15:31 UTC, edgarrmondragon requested changes
Would this use case be covered by https://github.com/meltano/sdk/issues/226?

2023-05-03 15:31 UTC, edgarrmondragon commented on tap_messagebird/streams.py
> +                )
```suggestion
                self.logger.info(
                    "Breaking after hitting a record with replication key %s < %s",
                    record_last_received_datetime,
                    starting_replication_key_value,
                )
```

2023-05-03 15:35 UTC, visch commented
> Would this use case be covered by [meltano/sdk#226](https://github.com/meltano/sdk/issues/226)?

Kind of, I think instead of "faking" it though we are actually reducing the number of requests dramatically as we stop iterating through pagination. So maybe that feature would solve this I guess it depends on how it's implemented!

2023-05-03 15:37 UTC, edgarrmondragon commented on tap_messagebird/streams.py
> +                )
It's not hate 😅, just convention and improves performance without a large dev cost when filtering out logs by level

2023-05-03 15:38 UTC, edgarrmondragon approved these changes

2023-05-03 15:41 UTC, merged